name: CD pipeline
on:
  push:
    branches:
      - main
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: devsareno
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create short SHA
        run: SHA="${{ github.sha }}" && export SHORT_SHA="${SHA::7}"
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: devsareno/jenkins-extended:latest,devsareno/jenkins-extended:$SHORT_SHA
